plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

remote_theme: mathew-j-davis/jekyll-true-minimal

github:
  show_downloads: false
  google_analytics: false
  is_project_page: false
title: Sle-132-biology-form-and-function
description: class notes for biology-form-and-function
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal