plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: jekyll-theme-minimal

github:
  show_downloads: false
  google_analytics: false
  is_project_page: false